version: '3'

services:
  database:
    build:
      context: ./database/
    container_name: ${SITE_NAME}-mariadb
    volumes:
      - ./database/sql/:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_DATABASE: ${SITE_NAME}
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: n5ddzMNzl3sQ8PHf
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "${MARIADB_EXTERNAL_PORT}:3306"

  php-apache:
    build:
      context: ./php-apache/
      args:
        TYPO3_VERSION: ${TYPO3_VERSION}
    container_name: ${SITE_NAME}-php-apache
    volumes:
      - ../fileadmin/:/var/www/html/fileadmin/
      - ../typo3conf/:/var/www/html/typo3conf/
      - ../typo3temp/:/var/www/html/typo3temp/
      - ../uploads/:/var/www/html/uploads/
      - ../src/:/var/www/html/src/
      - ../.htaccess:/var/www/html/.htaccess
      - ./php-apache/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php-apache/conf.d/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
      - ./php-apache/conf.d/default.ini:/usr/local/etc/php/conf.d/default.ini
    ports:
      - "80:80"
