<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "customext"
 *
 * Auto generated by Extension Builder 2019-04-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Custom Extension',
    'description' => 'Custom extension',
    'category' => 'plugin',
    'author' => 'SwissCode',
    'author_email' => 'info@swisscode.sk',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '12.4.0-12.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
