<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "customext"
 *
 * Auto generated by Extension Builder 2019-04-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Custom Extension',
    'description' => 'Custom extension',
    'category' => 'plugin',
    'author' => 'Juergen Furrer',
    'author_email' => 'juergen.furrer@gmail.com',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-11.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
